baseURL: "https://nullstellensatz.org/"
title: 0stellensatz
paginate: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  title: 0stellensatz
  description: ""
  keywords: [Blog]
  author: "Hilbert"
  # author: ["Me", "You"] # multiple authors
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set

  # home-info mode
  homeInfoParams:
    Title: "📝 Memorandum"
    Content: "Mostly notes to myself."

  socialIcons:
    - name: instagram
      url: "https://instagram.com/0stellensatz"
    - name: github
      url: "https://github.com/0stellensatz"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/0stellensatz/0stellensatz.github.io/blame/main/content"
    Text: "Source" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 0
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
